language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
addons:
  sonarcloud:
    organization: "mahmut-gundogdu-github"
script:
    - dotnet restore
    - dotnet build
    - sonar-scanner
